# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Win32-GUI-HyperLink
version:      0.11
version_from: lib\Win32\GUI\HyperLink.pm
installdirs:  site
requires:
    Test::More:                    0
    Win32::API:                    0
    Win32::GUI:                    1
    Win32::GUI::BitmapInline:      0.02

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
